eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10000/eureka/

server:
  port: 10003

spring:
  application:
    name: banker
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent_output: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Banker
    username: developer
    password: cuiyicong